[google]
project = "visualdb-1046"
zone = "us-east1-d"

[storage]
type = "google"
bucket = "esper"
path = "public/will"

[database]
type = "google"
name = "esper-dev"
user = "will"
password = "foobar"

[docker]
base_image_name = "esper-base"
device = "cpu"
extra_services = ["spark"]
dotfiles_dir = "~"

[ports]
nginx = 80
ipython = 8888
redis = 6379
frameserver = 7500
