[storage]
type = "local"

[database]
type = "local"       # Database is stored/run locally
user = "will"        # Username
password = "foobar"  # Password

[docker]
base_image_name = "esper-base"
device = "cpu"
extra_services = ["spark"]